# Generated by Django 3.2.4 on 2021-07-31 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smore', '0003_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exper_title', models.CharField(max_length=200)),
                ('exper_body', models.TextField()),
                ('exper_period', models.CharField(max_length=100)),
                ('exper_pub_date', models.DateTimeField()),
                ('exper_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('exper_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
