# Generated by Django 3.2.5 on 2021-07-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smore', '0005_auto_20210731_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
