# Generated by Django 3.2.5 on 2021-07-31 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='company_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='UserPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papers', models.FileField(blank=True, null=True, upload_to='files/')),
                ('companyFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
