# Generated by Django 3.2.4 on 2021-07-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smore', '0002_remove_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
