# Generated by Django 3.2.4 on 2021-07-31 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smore', '0004_experrec'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('itemFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smore.item')),
            ],
        ),
    ]
